
export const controlfamilyData = [
  {
		id: "1",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "2",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "3",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "4",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "5",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "6",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "6",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "6",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "6",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
  {
		id: "6",
		controlFamilyName: "Aged supplier advance",
		ControlFamilyDetails: "Human Resource Management",
		createdBy:"Racktim Guin",
		createdAt: "",
    edit:"",
    delete:"",
	},
 
];