import getCurrentDatetime from "../utils/getCurrentDatetime";

export const controlfamilyData = [
  {
    id: "1",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "2",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "3",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "4",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "5",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance 2",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance 6",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
  {
    id: "6",
    controlFamilyName: "Aged supplier advance",
    ControlFamilyDetails: "Human Resource Management",
    createdBy: "Racktim Guin",
    createdAt: getCurrentDatetime(),
  },
];
