export const nonCompilantTable=[
  {
    id:"1",
    accountname:"WPWCXlRH",
    accountnumber:"57726",
    address1:'it',
    address2:"govSakgBSvQIBVkXCiMW",
    address3:"zEkaFjjcXIL",
    cityname:"uRrLtrJJsmqnAfkfc",
    countryname:"Trinidad & Tobago",
    customeraccountstatus:"ACTIVE",
    customerclass:"ISGRpoGIEzVdSMxvYem",
    customerid:"52424",
    customername:"xxCvv59MxvlkGDmZsHFT",
    customernumber:"ABU DHABI AIRPORTS",
    description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized   gradually pleasure experiment magic nearby if themselves rhyme married anything",
    icaocode:"X8qbeE42Wke28RVGC",
    location:"Brunei",
    ouname:"nSbMHeznceyIj",
    overallcreditlimit:"ZzFaQOVXIu54D7m",
    partyid:"2041",
    partysitename:"ADAC",
    partysitenumber:"120110",
    postalcode:"",
    profile:"MNG_WLA",
    province:"",
    state:"",
  }, 
  {id:"2",
  accountname:"WPWCXlRH",
  accountnumber:"57726",
  address1:'it',
  address2:"govSakgBSvQIBVkXCiMW",
  address3:"zEkaFjjcXIL",
  cityname:"uRrLtrJJsmqnAfkfc",
  countryname:"Trinidad & Tobago",
  customeraccountstatus:"ACTIVE",
  customerclass:"ISGRpoGIEzVdSMxvYem",
  customerid:"52424",
  customername:"xxCvv59MxvlkGDmZsHFT",
  customernumber:"ABU DHABI AIRPORTS",
  description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized gradually pleasure experiment magic nearby if themselves rhyme married anything",
  icaocode:"X8qbeE42Wke28RVGC",
  location:"Brunei",
  ouname:"nSbMHeznceyIj",
  overallcreditlimit:"ZzFaQOVXIu54D7m",
  partyid:"2041",
  partysitename:"ADAC",
  partysitenumber:"120110",
  postalcode:"",
  profile:"MNG_WLA",
  province:"",
  state:"",
}, 
{id:"3",
accountname:"WPWCXlRH",
accountnumber:"57726",
address1:'it',
address2:"govSakgBSvQIBVkXCiMW",
address3:"zEkaFjjcXIL",
cityname:"uRrLtrJJsmqnAfkfc",
countryname:"Trinidad & Tobago",
customeraccountstatus:"ACTIVE",
customerclass:"ISGRpoGIEzVdSMxvYem",
customerid:"52424",
customername:"xxCvv59MxvlkGDmZsHFT",
customernumber:"ABU DHABI AIRPORTS",
description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized gradually pleasure experiment magic nearby if themselves rhyme married anything",
icaocode:"X8qbeE42Wke28RVGC",
location:"Brunei",
ouname:"nSbMHeznceyIj",
overallcreditlimit:"ZzFaQOVXIu54D7m",
partyid:"2041",
partysitename:"ADAC",
partysitenumber:"120110",
postalcode:"",
profile:"MNG_WLA",
province:"",
state:"",
},
{id:"4",
accountname:"WPWCXlRH",
accountnumber:"57726",
address1:'it',
address2:"govSakgBSvQIBVkXCiMW",
address3:"zEkaFjjcXIL",
cityname:"uRrLtrJJsmqnAfkfc",
countryname:"Trinidad & Tobago",
customeraccountstatus:"ACTIVE",
customerclass:"ISGRpoGIEzVdSMxvYem",
customerid:"52424",
customername:"xxCvv59MxvlkGDmZsHFT",
customernumber:"ABU DHABI AIRPORTS",
description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized gradually pleasure experiment magic nearby if themselves rhyme married anything",
icaocode:"X8qbeE42Wke28RVGC",
location:"Brunei",
ouname:"nSbMHeznceyIj",
overallcreditlimit:"ZzFaQOVXIu54D7m",
partyid:"2041",
partysitename:"ADAC",
partysitenumber:"120110",
postalcode:"",
profile:"MNG_WLA",
province:"",
state:"",
},
{id:"5",
accountname:"WPWCXlRH",
accountnumber:"57726",
address1:'it',
address2:"govSakgBSvQIBVkXCiMW",
address3:"zEkaFjjcXIL",
cityname:"uRrLtrJJsmqnAfkfc",
countryname:"Trinidad & Tobago",
customeraccountstatus:"ACTIVE",
customerclass:"ISGRpoGIEzVdSMxvYem",
customerid:"52424",
customername:"xxCvv59MxvlkGDmZsHFT",
customernumber:"ABU DHABI AIRPORTS",
description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized gradually pleasure experiment magic nearby if themselves rhyme married anything",
icaocode:"X8qbeE42Wke28RVGC",
location:"Brunei",
ouname:"nSbMHeznceyIj",
overallcreditlimit:"ZzFaQOVXIu54D7m",
partyid:"2041",
partysitename:"ADAC",
partysitenumber:"120110",
postalcode:"",
profile:"MNG_WLA",
province:"",
state:"",
},
{id:"6",
accountname:"WPWCXlRH",
accountnumber:"57726",
address1:'it',
address2:"govSakgBSvQIBVkXCiMW",
address3:"zEkaFjjcXIL",
cityname:"uRrLtrJJsmqnAfkfc",
countryname:"Trinidad & Tobago",
customeraccountstatus:"ACTIVE",
customerclass:"ISGRpoGIEzVdSMxvYem",
customerid:"52424",
customername:"xxCvv59MxvlkGDmZsHFT",
customernumber:"ABU DHABI AIRPORTS",
description:"man get brave sink locate classroom pound produce wonderful raise sand small moment organized gradually pleasure experiment magic nearby if themselves rhyme married anything",
icaocode:"X8qbeE42Wke28RVGC",
location:"Brunei",
ouname:"nSbMHeznceyIj",
overallcreditlimit:"ZzFaQOVXIu54D7m",
partyid:"2041",
partysitename:"ADAC",
partysitenumber:"120110",
postalcode:"",
profile:"MNG_WLA",
province:"",
state:"",
},
  
]