import getCurrentDatetime from "../utils/getCurrentDatetime";
export const simulateData = [
  {
    id: "1",
    controlAttributeName: "Creation Of dummy",
    reportName: "AD_U_GL_Accounts",
    syncAt: getCurrentDatetime(),
    syncedBy: "Alberta Walton",
    isSimulated: false,
    simulateAt: "",
    simulatedBy: "",
  },
  {
    id: "2",
    controlAttributeName: "Creation 2nd attribute",
    reportName: "AD_2nd_Report",
    syncAt: "2/3/2114",
    syncedBy: "Loretta Crawford",
    isSimulated: false,
    simulateAt: "",
    simulatedBy: "",
  },
  {
    id: "3",
    controlAttributeName: "Creation 3rd attribute",
    reportName: "AD_3rd_Report",
    syncAt: "8/29/2043",
    syncedBy: "David Jensen",
    isSimulated: false,
    simulateAt: "",
    simulatedBy: "",
  },
  {
    id: 69,
    controlAttributeName: "chmyWuFgzuBJvxlP",
    reportName: "dErUJTUAH",
    syncAt: "12/30/2112",
    syncedBy: "Tyler Cohen",
    isSimulated: true,
    simulateAt: "1/15/2049",
    simulatedBy: "Leah Armstrong",
  },
  {
    id: "764",
    controlAttributeName: "YxBSdMeZSDUUPPmKK",
    reportName: "BYpWlAXWcGDBIaFrmVy",
    syncAt: "12/8/2024",
    syncedBy: "Christian Howard",
    isSimulated: true,
    simulateAt: "1/14/2117",
    simulatedBy: "Ryan Johnston",
  },
  {
    id: 26,
    controlAttributeName: "YTADkhrGjMPWEwOHFAwL",
    reportName: "ijjTA",
    syncAt: "7/1/2055",
    syncedBy: "Jon Bass",
    isSimulated: true,
    simulateAt: "11/21/2107",
    simulatedBy: "Louisa Gibson",
  },
  {
    id: 7,
    controlAttributeName: "OqBbHQMuReUIZbS",
    reportName: "HIAxreMu",
    syncAt: "11/3/2083",
    syncedBy: "Wesley Norris",
    isSimulated: true,
    simulateAt: "9/2/2092",
    simulatedBy: "Betty Massey",
  },
  {
    id: 82,
    controlAttributeName: "nAOIowGnLMOXBi",
    reportName: "mXhAoA",
    syncAt: "12/4/2032",
    syncedBy: "Caleb Hodges",
    isSimulated: true,
    simulateAt: "9/30/2090",
    simulatedBy: "Rachel Carson",
  },
  {
    id: 33,
    controlAttributeName: "bzTnAgPllJtcWELh",
    reportName: "GSuHGvkHnmxABSzBhmrc",
    syncAt: "8/12/2079",
    syncedBy: "Fred Little",
    isSimulated: true,
    simulateAt: "7/1/2095",
    simulatedBy: "Wesley Nunez",
  },
  {
    id: 58,
    controlAttributeName: "qhTnTdmRVtKswAMsbeF",
    reportName: "brQRtVyGUrFVmQmGioTS",
    syncAt: "10/20/2083",
    syncedBy: "Polly Wise",
    isSimulated: true,
    simulateAt: "11/19/2062",
    simulatedBy: "Bessie Jimenez",
  },
  {
    id: 18,
    controlAttributeName: "lBODbJkPWGSaWnEE",
    reportName: "EMmalEkOznTIMP",
    syncAt: "2/2/2062",
    syncedBy: "Alex Holmes",
    isSimulated: true,
    simulateAt: "1/17/2090",
    simulatedBy: "Ida Luna",
  },
  {
    id: 6,
    controlAttributeName: "HBpVChBFMXqGda",
    reportName: "IdghQslvZyMo",
    syncAt: "11/30/2095",
    syncedBy: "Augusta Howard",
    isSimulated: true,
    simulateAt: "6/11/2097",
    simulatedBy: "Gene Rodriguez",
  },
  {
    id: 29,
    controlAttributeName: "jVYXfnhIMrNSl",
    reportName: "PemchyKrS",
    syncAt: "9/18/2075",
    syncedBy: "Nicholas Kelly",
    isSimulated: true,
    simulateAt: "8/9/2075",
    simulatedBy: "Dollie Dean",
  },
  {
    id: 16,
    controlAttributeName: "cUjKGLgHTgRYXeMYYcYb",
    reportName: "fxfisqHhQWUolBGuxi",
    syncAt: "5/17/2088",
    syncedBy: "Henry Moss",
    isSimulated: true,
    simulateAt: "9/16/2123",
    simulatedBy: "Oscar Ryan",
  },
  {
    id: 93,
    controlAttributeName: "FyipfwRuZcTYOZkL",
    reportName: "uNbqsgXkana",
    syncAt: "12/4/2070",
    syncedBy: "Marcus Norris",
    isSimulated: true,
    simulateAt: "2/22/2059",
    simulatedBy: "Derek Kennedy",
  },
  {
    id: 94,
    controlAttributeName: "mWfBf",
    reportName: "DKgWcp",
    syncAt: "2/16/2034",
    syncedBy: "Susie McKenzie",
    isSimulated: true,
    simulateAt: "2/5/2124",
    simulatedBy: "Chase McDaniel",
  },
  {
    id: 74,
    controlAttributeName: "EdiedvQk",
    reportName: "aLYyr",
    syncAt: "8/23/2077",
    syncedBy: "Mollie Black",
    isSimulated: true,
    simulateAt: "6/19/2055",
    simulatedBy: "Arthur Rodriquez",
  },
  {
    id: 2,
    controlAttributeName: "HVeLiXutiw",
    reportName: "sQcTeqUZmMeiVTOVGA",
    syncAt: "5/13/2077",
    syncedBy: "Dale Griffith",
    isSimulated: true,
    simulateAt: "1/15/2026",
    simulatedBy: "Betty Greer",
  },
  {
    id: 21,
    controlAttributeName: "qPhCBoSvjInMlwcfP",
    reportName: "iagnFGlQShEoV",
    syncAt: "3/1/2066",
    syncedBy: "Ralph Alvarez",
    isSimulated: true,
    simulateAt: "3/19/2065",
    simulatedBy: "Lydia Santos",
  },
  {
    id: 33,
    controlAttributeName: "keyOTuocLDuiegerU",
    reportName: "qzZmgogmg",
    syncAt: "10/13/2113",
    syncedBy: "Joseph Horton",
    isSimulated: true,
    simulateAt: "11/14/2108",
    simulatedBy: "Belle Bowers",
  },
  {
    id: 26,
    controlAttributeName: "wbZMCSOeZBA",
    reportName: "rIzjxrHdpErgWrMahFq",
    syncAt: "10/15/2051",
    syncedBy: "Kevin Kim",
    isSimulated: true,
    simulateAt: "5/25/2034",
    simulatedBy: "Sylvia Bates",
  },
  {
    id: 36,
    controlAttributeName: "OjcLzLTTmEEAPWs",
    reportName: "IZXoVTFEgjLzOly",
    syncAt: "2/17/2049",
    syncedBy: "Howard Cross",
    isSimulated: true,
    simulateAt: "10/4/2056",
    simulatedBy: "Emily Park",
  },
  {
    id: 5,
    controlAttributeName: "IpqlgqUoEe",
    reportName: "PheCw",
    syncAt: "9/30/2040",
    syncedBy: "Jorge Wilkins",
    isSimulated: true,
    simulateAt: "7/23/2120",
    simulatedBy: "Leonard Mendoza",
  },
  {
    id: 3,
    controlAttributeName: "OeMBNGyHX",
    reportName: "aBgyHmuvNakwLS",
    syncAt: "4/21/2078",
    syncedBy: "Agnes Mills",
    isSimulated: true,
    simulateAt: "10/11/2070",
    simulatedBy: "Logan Colon",
  },
  {
    id: 78,
    controlAttributeName: "MmlOubfBWGOtgWHyX",
    reportName: "WtbGCPfllIWGwzL",
    syncAt: "10/17/2052",
    syncedBy: "Lottie Murphy",
    isSimulated: true,
    simulateAt: "8/27/2034",
    simulatedBy: "Jerry Ballard",
  },
  {
    id: 3,
    controlAttributeName: "kwheyn",
    reportName: "cEwpLuWVFdg",
    syncAt: "9/13/2104",
    syncedBy: "Dustin Day",
    isSimulated: true,
    simulateAt: "9/3/2107",
    simulatedBy: "Jimmy Page",
  },
  {
    id: 97,
    controlAttributeName: "IYjaG",
    reportName: "QNyLJlJlenVbQTEfsGbM",
    syncAt: "2/28/2080",
    syncedBy: "Scott Marsh",
    isSimulated: true,
    simulateAt: "8/6/2090",
    simulatedBy: "Josephine Walker",
  },
  {
    id: 13,
    controlAttributeName: "tprMJKINj",
    reportName: "iqfbbAqU",
    syncAt: "3/10/2123",
    syncedBy: "Callie Dawson",
    isSimulated: true,
    simulateAt: "12/3/2026",
    simulatedBy: "Bernice Flores",
  },
  {
    id: 62,
    controlAttributeName: "wGBTuaStWuoj",
    reportName: "GplJTzXbmoOTduMFUsb",
    syncAt: "2/13/2087",
    syncedBy: "Leon Anderson",
    isSimulated: true,
    simulateAt: "10/19/2034",
    simulatedBy: "Cynthia Becker",
  },
  {
    id: 86,
    controlAttributeName: "QRBEaPeYjfkfZ",
    reportName: "LVRIZCvU",
    syncAt: "8/28/2077",
    syncedBy: "Christopher Arnold",
    isSimulated: true,
    simulateAt: "3/2/2085",
    simulatedBy: "Willie Phillips",
  },
  {
    id: 33,
    controlAttributeName: "RIfxXySYCuU",
    reportName: "qSvNhJmTnjrFZxIVDrb",
    syncAt: "2/11/2065",
    syncedBy: "Eric King",
    isSimulated: true,
    simulateAt: "11/8/2069",
    simulatedBy: "Albert Nunez",
  },
  {
    id: 29,
    controlAttributeName: "FxhLtlkprNh",
    reportName: "akeQGzFbnUjtaiCEMx",
    syncAt: "8/31/2038",
    syncedBy: "Cynthia Wood",
    isSimulated: true,
    simulateAt: "8/10/2090",
    simulatedBy: "Nell Manning",
  },
  {
    id: 25,
    controlAttributeName: "fnittemip",
    reportName: "sQNuwIZHCqBQFqt",
    syncAt: "8/2/2082",
    syncedBy: "Austin McGee",
    isSimulated: true,
    simulateAt: "10/8/2038",
    simulatedBy: "Dollie Wise",
  },
  {
    id: 75,
    controlAttributeName: "naoUqLymhk",
    reportName: "yzIfst",
    syncAt: "1/3/2109",
    syncedBy: "Allen Chandler",
    isSimulated: true,
    simulateAt: "7/26/2108",
    simulatedBy: "Glenn Adkins",
  },
  {
    id: 78,
    controlAttributeName: "PGHrBPzwQZSMALyByRUG",
    reportName: "YffaARxxSogZpigc",
    syncAt: "9/13/2084",
    syncedBy: "Melvin Gordon",
    isSimulated: true,
    simulateAt: "6/2/2086",
    simulatedBy: "May Arnold",
  },
  {
    id: 64,
    controlAttributeName: "wxBVQznEyibwdgF",
    reportName: "vFqKTVGvnS",
    syncAt: "8/9/2031",
    syncedBy: "Jean Green",
    isSimulated: true,
    simulateAt: "8/25/2049",
    simulatedBy: "Joe Lopez",
  },
  {
    id: 62,
    controlAttributeName: "GScuZez",
    reportName: "OhRtxrdx",
    syncAt: "7/12/2105",
    syncedBy: "Ola Cobb",
    isSimulated: true,
    simulateAt: "8/27/2073",
    simulatedBy: "Warren Cummings",
  },
  {
    id: 90,
    controlAttributeName: "lxTRTavV",
    reportName: "PXRvjni",
    syncAt: "1/31/2048",
    syncedBy: "Caleb Taylor",
    isSimulated: true,
    simulateAt: "2/22/2094",
    simulatedBy: "Hannah Pratt",
  },
  {
    id: 92,
    controlAttributeName: "zBumu",
    reportName: "oasagrBxGeXOhfte",
    syncAt: "6/3/2114",
    syncedBy: "Adelaide Dean",
    isSimulated: true,
    simulateAt: "6/29/2060",
    simulatedBy: "Sean May",
  },
  {
    id: 66,
    controlAttributeName: "JWitDehCHw",
    reportName: "uCumyTRBHqHA",
    syncAt: "2/18/2039",
    syncedBy: "Keith Pratt",
    isSimulated: true,
    simulateAt: "9/12/2059",
    simulatedBy: "Jacob Clark",
  },
  {
    id: 100,
    controlAttributeName: "zcYNZJJUhE",
    reportName: "VuicsRdloLUdoQBlMGkx",
    syncAt: "9/20/2098",
    syncedBy: "Georgia Henderson",
    isSimulated: true,
    simulateAt: "1/24/2075",
    simulatedBy: "Edna Murray",
  },
  {
    id: 78,
    controlAttributeName: "FxqmfPMHHDLuCPDTnvNI",
    reportName: "NEafTUYsIo",
    syncAt: "11/3/2040",
    syncedBy: "Henrietta Moss",
    isSimulated: true,
    simulateAt: "2/6/2115",
    simulatedBy: "Alvin Diaz",
  },
  {
    id: 55,
    controlAttributeName: "GFcyVbCeyve",
    reportName: "GUYYuTLXbMcFNM",
    syncAt: "5/17/2096",
    syncedBy: "Maurice Watts",
    isSimulated: true,
    simulateAt: "5/27/2081",
    simulatedBy: "Hannah Scott",
  },
  {
    id: 5,
    controlAttributeName: "ZtLhzQtn",
    reportName: "czYXDVQsVOfTbvxk",
    syncAt: "9/9/2111",
    syncedBy: "Antonio Barrett",
    isSimulated: true,
    simulateAt: "8/17/2031",
    simulatedBy: "Alejandro Cole",
  },
  {
    id: 30,
    controlAttributeName: "uLMuhluhIYN",
    reportName: "rxyirbbzP",
    syncAt: "10/28/2096",
    syncedBy: "Polly Wilson",
    isSimulated: true,
    simulateAt: "9/4/2046",
    simulatedBy: "Leroy Lyons",
  },
  {
    id: 80,
    controlAttributeName: "CguhFdGfKMsJKdZok",
    reportName: "TMdzaYvtpD",
    syncAt: "9/23/2061",
    syncedBy: "Elmer Martin",
    isSimulated: true,
    simulateAt: "6/18/2049",
    simulatedBy: "Todd Brown",
  },
  {
    id: 77,
    controlAttributeName: "aaURVw",
    reportName: "jHqqIvydZCmzYZSyapjE",
    syncAt: "5/2/2050",
    syncedBy: "Jorge Townsend",
    isSimulated: true,
    simulateAt: "8/6/2058",
    simulatedBy: "Ophelia Robbins",
  },
  {
    id: 41,
    controlAttributeName: "IUXwRIuUHAHqmI",
    reportName: "tQBAyDAGnWL",
    syncAt: "11/22/2057",
    syncedBy: "Kathryn Simpson",
    isSimulated: true,
    simulateAt: "7/14/2097",
    simulatedBy: "Alta Sandoval",
  },
  {
    id: 44,
    controlAttributeName: "iGoFXNRHPWmz",
    reportName: "cCzZhrzMqjfMuZfG",
    syncAt: "10/4/2042",
    syncedBy: "Eunice Reed",
    isSimulated: true,
    simulateAt: "10/23/2112",
    simulatedBy: "Lou Harris",
  },
  {
    id: 62,
    controlAttributeName: "aDBiH",
    reportName: "rJJHdzgHkCll",
    syncAt: "11/21/2117",
    syncedBy: "Maude Rose",
    isSimulated: true,
    simulateAt: "7/31/2105",
    simulatedBy: "Brian Briggs",
  },
  {
    id: 31,
    controlAttributeName: "TlRlcaAwwZxatbRI",
    reportName: "FGsfBMwoflqh",
    syncAt: "6/13/2078",
    syncedBy: "Helena Young",
    isSimulated: true,
    simulateAt: "5/13/2062",
    simulatedBy: "Virgie Conner",
  },
  {
    id: 26,
    controlAttributeName: "wVytAs",
    reportName: "nTcSsWqQUXqVitQkufpC",
    syncAt: "12/10/2066",
    syncedBy: "Blanche Santiago",
    isSimulated: true,
    simulateAt: "9/10/2039",
    simulatedBy: "Earl Mullins",
  },
];
