export const userData = [
  {
    id: 75,
    name: "Adam Waters",
    email: "leriblah@bimvigiwi.ec",
    password: "123456",
    role: "USER",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: false,
      report: false,
      roles: false,
      typeOfcontrol: false,
    },
  },
  {
    id: 1,
    name: "Blanche McDaniel",
    email: "keriplar@konid.bh",
    password: "123456",
    role: "USER",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: false,
      report: false,
      roles: false,
      typeOfcontrol: false,
    },
  },
  {
    id: 12,
    name: "Dylan Hopkins",
    password: "123456",
    email: "if@pehkoza.co",
    role: "USER",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: false,
      report: false,
      roles: false,
      typeOfcontrol: false,
    },
  },
  {
    id: 58,
    name: "Cody Fletcher",
    password: "123456",
    email: "nigta@azfodci.tt",
    role: "ADMIN",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: true,
      report: true,
      roles: true,
      typeOfcontrol: true,
    },
  },
  {
    id: 87,
    name: "Josephine Graves",
    password: "123456",
    email: "zaugu@mava.gm",
    role: "USER",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: false,
      report: false,
      roles: false,
      typeOfcontrol: false,
    },
  },
  {
    id: 31,
    name: "Isabelle Hunter",
    password: "123456",
    email: "bauv@imidaho.py",
    role: "ADMIN",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: true,
      report: true,
      roles: true,
      typeOfcontrol: true,
    },
  },
  {
    id: 1,
    name: "Inez Roberson",
    password: "123456",
    email: "ha@ubfi.ie",
    role: "ADMIN",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: true,
      report: true,
      roles: true,
      typeOfcontrol: true,
    },
  },
  {
    id: 72,
    name: "Prity Singh",
    password: "123456",
    email: "prity@dev.com",
    role: "ADMIN",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: true,
      report: true,
      roles: true,
      typeOfcontrol: true,
    },
  },
  {
    id: 964,
    name: "Suman Mondal",
    password: "123456",
    email: "suman@dev.com",
    otp: "123456",
    role: "ADMIN",
    permissions: {
      controlAttribute: true,
      controlFamily: true,
      controlLogic: true,
      dashboard: true,
      dataLoad: true,
      report: true,
      roles: true,
      typeOfcontrol: true,
    },
  },
];
