export const userData = [
    {
        id: 75,
        fName: "Adam",
        lName: "Waters",
        email: "leriblah@bimvigiwi.ec",
        password: "123456",
        role: "USER",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: false,
            report: false,
            roles: false,
            typeOfcontrol: false,
        },
    },
    {
        id: 1,
        fName: "Blanche",
        lName: "McDaniel",
        email: "keriplar@konid.bh",
        password: "123456",
        role: "USER",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: false,
            report: false,
            roles: false,
            typeOfcontrol: false,
        },
    },
    {
        id: 12,
        fName: "Dylan",
        lName: "Hopkins",
        password: "123456",
        email: "if@pehkoza.co",
        role: "USER",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: false,
            report: false,
            roles: false,
            typeOfcontrol: false,
        },
    },
    {
        id: 58,
        fName: "Cody",
        lName: "Fletcher",
        password: "123456",
        email: "nigta@azfodci.tt",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
    {
        id: 87,
        fName: "Josephine",
        lName: "Graves",
        password: "123456",
        email: "zaugu@mava.gm",
        role: "USER",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: false,
            report: false,
            roles: false,
            typeOfcontrol: false,
        },
    },
    {
        id: 31,
        fName: "Isabelle",
        lName: "Hunter",
        password: "123456",
        email: "bauv@imidaho.py",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
    {
        id: 1,
        fName: "Inez",
        lName: "Roberson",
        password: "123456",
        email: "ha@ubfi.ie",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
    {
        id: 72,
        fName: "Prity",
        lName: "Singh",
        password: "123456",
        email: "prity@dev.com",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
    {
        id: 964,
        fName: "Suman",
        lName: "Mondal",
        password: "123456",
        email: "suman@dev.com",
        otp: "123456",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
    {
        id: 9640,
        fName: "Admin",
        lName: "",
        password: "123456",
        email: "admin@admin.com",
        otp: "123456",
        role: "ADMIN",
        permissions: {
            controlAttribute: true,
            controlFamily: true,
            controlLogic: true,
            dashboard: true,
            dataLoad: true,
            report: true,
            roles: true,
            typeOfcontrol: true,
        },
    },
];
