export const userData = [
	{
		id: 75,
		name: "Adam Waters",
		email: "leriblah@bimvigiwi.ec",
		role: "USER",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: false,
			report: false,
			roles: false,
			typeOfcontrol: false,
		},
	},
	{
		id: 1,
		name: "Blanche McDaniel",
		email: "keriplar@konid.bh",
		role: "USER",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: false,
			report: false,
			roles: false,
			typeOfcontrol: false,
		},
	},
	{
		id: 12,
		name: "Dylan Hopkins",
		email: "if@pehkoza.co",
		role: "USER",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: false,
			report: false,
			roles: false,
			typeOfcontrol: false,
		},
	},
	{
		id: 58,
		name: "Cody Fletcher",
		email: "nigta@azfodci.tt",
		role: "ADMIN",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: true,
			report: true,
			roles: true,
			typeOfcontrol: true,
		},
	},
	{
		id: 87,
		name: "Josephine Graves",
		email: "zaugu@mava.gm",
		role: "USER",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: false,
			report: false,
			roles: false,
			typeOfcontrol: false,
		},
	},
	{
		id: 31,
		name: "Isabelle Hunter",
		email: "bauv@imidaho.py",
		role: "ADMIN",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: true,
			report: true,
			roles: true,
			typeOfcontrol: true,
		},
	},
	{
		id: 1,
		name: "Inez Roberson",
		email: "ha@ubfi.ie",
		role: "ADMIN",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: true,
			report: true,
			roles: true,
			typeOfcontrol: true,
		},
	},
	{
		id: 72,
		name: "Fanny Wilkins",
		email: "hi@mo.cc",
		role: "USER",
		permissions: {
			controlAttribute: true,
			controlFamily: true,
			controlLogic: true,
			dashboard: true,
			dataLoad: false,
			report: false,
			roles: false,
			typeOfcontrol: false,
		},
	},
];
